#!/usr/bin/env node

const fs = require("fs");
const http = require("http");

const esbuild = require("esbuild");

const buildJS = ({ src, dest, dev }) => {
  try {
    esbuild.build({
      entryPoints: [src],
      outfile: dest,
      bundle: true,
      minify: !dev,
      watch: dev && {
        onRebuild(err, result) {
          err
            ? console.error(`build js errored: ${err}`)
            : console.error("build js successful");
        },
      },
      define: {
        MEMOIR_ADMIN_ENABLED: `"${dev}"`,
        MEMOIR_API_KEY: dev ? `${process.env.MEMOIR_API_KEY}` : '""',
        MEMOIR_API_URL: dev
          ? '"http://localhost:8080"'
          : '"https://api.iamdjriff.co.uk"',
        MEMOIR_CDN_URL: dev
          ? '"https://memoir-artwork-development.s3.amazonaws.com"'
          : '"https://d4vv6ayb6g3d4.cloudfront.net"',
      },
    });
  } catch {}
};

const serve = async (servedir, listen) => {
  const { host, port } = await esbuild.serve({ servedir }, {});

  const proxy = http.createServer((req, res) => {
    const forwardRequest = (path) => {
      const options = {
        hostname: host,
        port,
        path,
        method: req.method,
        headers: req.headers,
      };

      const proxyReq = http.request(options, (proxyRes) => {
        if (proxyRes.statusCode === 404) {
          return forwardRequest("/");
        }

        res.writeHead(proxyRes.statusCode, proxyRes.headers);
        proxyRes.pipe(res, { end: true });
      });

      req.pipe(proxyReq, { end: true });
    };

    forwardRequest(req.url);
  });

  proxy.listen(listen);
};

const dev = process.argv[2] !== "--build";

buildJS({
  src: "src/index.tsx",
  dest: "public/app.js",
  dev,
});

if (dev) {
  serve("public", 10001);
  console.error("listening on http://localhost:10001");
}
